#!/usr/bin/env python3

import os

env = SConscript("../godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp") + Glob("src/*.mm")

if env["platform"] == "macos":
	env.Append(LINKFLAGS=["-framework", "AppKit"])

library = env.SharedLibrary(
	"bin/libnotch_bridge.{}.{}.framework/libnotch_bridge.{}.{}".format(
		env["platform"],
		env["target"],
		env["platform"],
		env["target"],
	),
	source=sources,
)

Default(library)
